.Dd May 11, 2017
.Dt BNS 1
.Os

.Sh NAME
.Nm bns
.Nd adjust screen brightness on my machine

.Sh SYNOPSIS
.Nm bns
.Ar new

.Sh DESCRIPTION
Set the screen brightness to
.Ar new ,
usually a number between 0 and 255.

.Sh FILES
.Bl -tag -width Ds
.It Pa /sys/devices/pci0000:00/0000:00:01.0/drm/card0/card0-eDP-1/radeo_bl0/brightness
The file for controlling the brightness.
.El

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
.Nm
uses a hardcoded path.

.Sh SEE ALSO
.Xr echo 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
