.Dd May 11, 2017
.Dt BOMB 1
.Os

.Sh NAME
.Nm bomb
.Nd start a fork bomb

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
spawns two processes of itself in the background
recursively. This is also called a fork-bomb.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr fork 2 ,
.Xr exec 3 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
