.TH CHAN 1
.SH NAME
\fBchan\fR \- substitute in files

.SH SYNOPSIS
\fBchan\fR FROM TO FILES

.SH DESCRIPTION
\fBchan\fR is a utility to substitute regular expressions in FILES
matching a regular expression. For every match of FROM in FILES, it
is replaced by the ed-replacement expression TO.

.SH EXAMPLES
.TP
.B chan '\e<\e([0-9A-Fa-f]\e+\e)h' '0x\e1' *.asm
changes the style of the  hexadecimal numbers in all files having the extension 'asm'.

.SH STATUS
0 on success and 1 when it prints the help message.

.SH SEE ALSO
.IR regex(7),
.IR ed(1)

.SH BUGS
Normally, ed only accepts basic regular expressions, but extended
regular expressions would be nice for FROM and TO. Workaround: use
a better version of ed (9base for example).

.SH AUTHOR
Some bastard spent too much time hacking this together. I heard his
e-mail address is pranomestro@gmail.com.
