.TH CHAN 1
.SH NAME
chan \- substitute in files

.SH SYNOPSIS
chan from to files

.SH DESCRIPTION
chan is a utility to substitute regular expressions in files
matching a regular expression. For every match of from in files, it
is replaced by the ed-replacement expression to.

.SH EXAMPLES
.PP
.fi
.RS
$ chan '\e<\e([0-9A-Fa-f]\e+\e)h' '0x\e1' *.asm
.RE
.fi
changes the style of the hexadecimal numbers in all files having the extension 'asm'.

.SH STATUS
0 on success and 1 when it prints the usage.

.SH BUGS
Normally, ed only accepts basic regular expressions, but extended
regular expressions would be nice for FROM and TO.
.br
Workaround: use a better version of ed (9base for example).

.SH "SEE ALSO"
.IR regex(7),
.IR ed(1).

.SH AUTHOR
Some bastard spent too much time hacking this together. I heard his
e-mail address is pranomestro@gmail.com.
