.Dd May 11, 2017
.Dt CHV 1
.Os

.Sh NAME
.Nm chv
.Nd change the volume

.Sh SYNOPSIS
.Nm
.Ar -+perc

.Sh DESCRIPTION
Change the current volume by the given percentage
.Ar perc .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr alsamixer 1 ,
.Xr amixer 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
