.Dd May 11, 2017
.Dt CNT 1
.Os

.Sh NAME
.Nm cnt
.Nd center a window

.Sh SYNOPSIS
.Nm
.Op Ar win

.Sh DESCRIPTION
.Nm
puts the given (or current) window in the middle of the screen.

.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev BW
The current window border width.
.El

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr wmutils 1 ,
.Xr wmv 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
