.Dd June 15, 2017
.Dt DEC 1
.Os

.Sh NAME
.Nm dec
.Nd decrypt pgp input

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
decrypts ascii armored pgp encrypted input. It acts as a wrapper for
.Xr gpg 1 .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr gpg2 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
