.Dd June 28, 2017
.Dt DWPD 1
.Os

.Sh NAME
.Nm dwpd
.Nd attempt to decrypt input if it contains pgp data

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
checks if its input contains pgp data (indicated by
.Dq -----BEGIN PGP MESSAGE-----
and
.Dq -----END PGP MESSAGE-----
and outputs the possibly decrypted content.

.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/dwpd.XXXXXX
Temporary file for storing the input.
.El

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr gpg2 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
