.TH ECP 1
.SH NAME
ecp \- somehow extended cp

.SH SYNOPSIS
ecp [-t] FROM TO

.SH DESCRIPTION
ecp is a simple wrapper for cp, using basic regular expressions.
I takes two arguments: FROM is an expression that determines the files
that have to be copied, TO is a sed-replacement expression for the target file.

.SH OPTIONS
.TP
.BI \-t
overwrite existing files.

.SH EXAMPLES
.PP
.fi
.RS
$ ecp '\e(.*\e)\e.sh$' '\e1.1'
.RE
.fi
was used during the creation of ecp, and copies every file with the
extension '.sh' to the the corresponding file with the extension '.1'.

.SH STATUS
0 on success, 1 when it prints the usage, 2 when given a bad option,
and 3 if it is asked to replace an already existing file.

.SH "SEE ALSO"
.IR regex(7),
.IR sed(1),
.IR emv(1).

.SH AUTHOR
Bug reports to pranomestro@gmail.com
