.Dd May 11, 2017
.Dt ELL 1
.Os

.Sh NAME
.Nm ell
.Nd ellipse each input line

.Sh SYNOPSIS
.Nm
.Op Ar len

.Sh DESCRIPTION
.Nm
replaces the characters after the first
.Ar len
ones (default 80) with the string
.Dq ...
in every input line.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr sed 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
