.Dd May 11, 2017
.Dt EMPTY 1
.Os

.Sh NAME
.Nm empty
.Nd remove all files from ~/trash/

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
deletes all files and directories in $HOME/trash/.

.Sh FILES
.Bl -tag -width Ds
.It Pa ~/trash/
The directory for deleted files and directories.
.El

.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev HOME
The home directory where the trash directory is located.
.El

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr r 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
