.TH EMV 1
.SH NAME
emv \- somehow extended mv

.SH SYNOPSIS
emv [-t] from TO

.SH DESCRIPTION
emv renames files based on regular expressions.
I takes two arguments: from is a basic regular expression that determines the
files that have to be renamed, to is a sed-replacement expression for the
target file.

.SH OPTIONS
.TP
.BI -t
overwrite existing files.

.SH EXAMPLES
.PP
.fi
.RS
$ emv '^a' 'm_&'
.RE
.fi
moves every file matching '^a' to a file with the same
name with the prefix 'm_', so 'abaco.c' becomes 'm_abaco.c'.

.SH STATUS
0 on success, 1 when it prints the usage, 2 when given a bad option,
and 3 if it is asked to replace an already existing file.

.SH "SEE ALSO"
.IR regex(7),
.IR sed(1),
.IR ecp(1),
.IR zmv(1).

.SH AUTHOR
In the unlikely case of a (real) bug (or just tell me how great this is), just
mail me: pranomestro@gmail.com (don't be shy!).
