.TH ERM 1
.SH NAME
\fBerm\fR \- grep | xargs rm

.SH SYNOPSIS
\fBerm\fR PATTERN

.SH DESCRIPTION
For every file in the current directory matching PATTERN (a basic regular expression), remove the file.

.SH EXAMPLES
\fBerm 'ata$'\fR removes every file ending with 'ata'.

.SH STATUS
0 on success and 1 when it prints the help message.

.SH "SEE ALSO"
\fBregex(7)\fR, \fBemv(1)\fR and \fBerm(1)\fR.

.SH BUGS
Accepts only basic regular expressions and is very dangerous.

.SH AUTHOR
Me (a.regenfuss@gmx.de).
