.Dd June 22, 2017
.Dt FDS 1
.Os

.Sh NAME
.Nm fds
.Nd print the flattened directory structure

.Sh SYNOPSIS
.Nm
.Op Ar dir

.Sh DESCRIPTION
.Nm
prints the flattened directory structure of the current directory or
.Ar dir .
It is similar to tree, but has less options.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr du 1 ,
.Xr ls 1 ,
.Xr tree 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
