.Dd June 28, 2017
.Dt FINDUP 1
.Os

.Sh NAME
.Nm findup
.Nd find a file in directories above

.Sh SYNOPSIS
.Nm
.Ar name

.Sh DESCRIPTION
.Nm
prints the relative path of
.Ar name
in the directories above or nothing when no file with the filename has
been found.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr find 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
