.Dd December 19, 2018
.Dt FULG 1
.Os

.Sh NAME
.Nm fulg
.Nd wrapper for fulgurate

.Sh SYNOPSIS
.Nm
.Ar add|run|imp|import|shsh|schowsched|schow-schedule
.Op Ar ...

.Sh DESCRIPTION
.Nm
.Ar comm
executes
.Dl fulgurate-comm
with the rest of the provided arguments.
.Ar imp
is an alias for
.Ar import,
.Ar shsh
and
.Ar schowsched
are aliases for
.Ar schow-schedule .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
Mnemosyne, Anki

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
