.Dd May 11, 2017
.Dt GM 1
.Os

.Sh NAME
.Nm gm
.Nd execute a command in a set of git repositories

.Sh SYNOPSIS
.Nm
.Ar action
.Ar srcdir
.Ar srcfile

.Sh DESCRIPTION
.Nm
executes
.Ar action
in each directory in
.Ar srcfile
in
.Ar srcdir .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr git 1 ,
.Xr gitpost 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
