.Dd June 29, 2017
.Dt LG 1
.Os

.Sh NAME
.Nm lg
.Nd convert all non-whitespace to underscores

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
converts all non-whitespace characters of the standard input to
underscores. This can be used in
.Dq guess the programming language by the whitespace
(line-games, hence the name).

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr tr 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
