.Dd May 11, 2017
.Dt MCP 1
.Os

.Sh NAME
.Nm mcp
.Nd copy a file to multiple destinations

.Sh SYNOPSIS
.Nm
.Ar src
.Ar dest1
.Op Ar ...

.Sh DESCRIPTION
.Nm
copies
.Ar src
to all
.Ar destn .
Existing files are overwritten.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr cp 1 ,
.Xr ecp 1 ,
.Xr emv 1 ,
.Xr pcp 1 ,
.Xr pmv 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
