.TH MG 1
.SH NAME
mg \- move to generic names

.SH SYNOPSIS
mg [-t] FILES

.SH DESCRIPTION
mg renames every of it's argument to a generic name. Unless given
the option '-t', it doesn't replace already existing files.

.SH EXAMPLES
.TP
.B mg *.png
gives all '.png' files in the current directory generic names.

.SH STATUS
0 on success and 1 when it doesn't replace an already existing file.

.SH SEE ALSO
.IR gen(1).

.SH BUGS
mg needs an installed version of gen(1).

.SH AUTHOR
His e-mail address a.regenfuss@gmx.de
