.TH NT 1
.SH NAME
\fBnt\fR \- find broken symlinks

.SH SYNOPSIS
\fBnt\fR [DIR]

.SH DESCRIPTION
\fBnt\fR searches for broken symbolic links recursively in
the directory DIR, if not provided, the current directory.

.SH "SEE ALSO"
\fBfind(1)\fR.

.SH BUGS
Symbolic links are horrible, I sure there are some corner cases that
are not covered with this program.

.SH AUTHOR
This is a 13.65% project by a.regenfuss@gmx.de.
