.TH NT 1
.SH NAME
\fBnt\fR \- find broken symlinks

.SH SYNOPSIS
\fBnt\fR DIR

.SH DESCRIPTION
\fBnt\fR searches for broken symbolic links recursively in the directory DIR.

.SH "SEE ALSO"
\fBfind(1)\fR.

.SH BUGS
The idea of symbolic links is not nearly exploited, several bugs are possible, but not found yet.

.SH AUTHOR
This is a 13.65% project by a.regenfuss@gmx.de.
