.Dd May 11, 2017
.Dt PARTSUM 1
.Os

.Sh NAME
.Nm partsum
.Nd print the numerical difference between input lines

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
expects one number per input line, and prints the difference between
two succeeding lines.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr awk 1 ,
.Xr seq 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
