.Dd May 11, 2017
.Dt PCP 1
.Os

.Sh NAME
.Nm pcp
.Nd pairwise copy

.Sh SYNOPSIS
.Nm
.Op src1 dest1
.Op ...
.Op srcn destn

.Sh DESCRIPTION
.Nm
copies its arguments pairwise, for example
.Ar src1
ist copied to
.Ar dest1 .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr cp 1 ,
.Xr mcp 1 ,
.Xr pmv 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
