.Dd July 7, 2017
.Dt PFM 1
.Os

.Sh NAME
.Nm pfm
.Nd list commits per day with commits

.Sh SYNOPSIS
.Nm pfm

.Sh DESCRIPTION
.Nm
prints the number of commits on days with commits for the last 150
of these days (or as many as are available) for the current git repo,
one number per line.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr git 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
