.Dd July 8, 2017
.Dt PLAY 1
.Os

.Sh NAME
.Nm play
.Nd play an ogg file in the background

.Sh SYNOPSIS
.Nm play
.Ar files

.Sh DESCRIPTION
.Nm
plays
.Ar files
in the background using
.Xr ogg123 1 .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr ogg123 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
