.Dd July 10, 2017
.Dt PMV 1
.Os

.Sh NAME
.Nm pmv
.Nd rename files pairwise

.Sh SYNOPSIS
.Nm
.Op Ar src1 dest1
.Op ...
.Op Ar srcn destn

.Sh DESCRIPTION
.Nm
renames its arguments pairwise, for example
.Ar src1
is moved to
.Ar dest1 .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr mcp 1 ,
.Xr mv 1 ,
.Xr pcp 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
