.Dd July 13, 2017
.Dt RAT-FRIENDDIR 1
.Os

.Sh NAME
.Nm rat-frienddir
.Nd create a directory with friendnames

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
creates the directory
.Dq friends/
and in it creates a soft link to every
.Xr ratox 1
directory which represents a friend. The nickname of each friend is the
name of the soft link.

.Sh FILES
.Bl -tag -width Ds
.It Pa friends/
The directory containing the links to the friend directories.
.El

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr ratox 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
