.Dd May 11, 2017
.Dt SHP 1
.Os

.Sh NAME
.Nm
.Nd send a patch to the suckless hackers mailing list

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
sends the last commit in the current git repository as a patch to the suckless
hackers mailing list.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr git-send-email .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
