.Dd July 19, 2017
.Dt STS 1
.Os

.Sh NAME
.Nm sts
.Nd start sam in the background

.Sh SYNOPSIS
.Nm
.Op Ar args

.Sh DESCRIPTION
.Nm
is used to start
.Xr sam 1
in the background with
.Ar args .

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr sam 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
