.Dd May 11, 2017
.Dt TAGESSCHAU 1
.Os

.Sh NAME
.Nm tagesschau
.Nd play the tagesschau of yesterday

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
plays the tagesschau from yesterday with
.Xr mpv 1 .

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
The format of the file on the tagesschau servers is not yet well
understood.  It may not work.

.Sh SEE ALSO
.Xr mpv 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
