.Dd August 6, 2019
.Dt TFLT 1
.Os

.Sh NAME
.Nm tflt
.Nd run the git history of a file through a filter

.Sh SYNOPSIS
.Nm
.Ar filter
.Ar file

.Sh DESCRIPTION
.Nm
pipes
.Ar file
through
.Ar filter
for each commit, from the earliest to the latest.

.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/tlc.XXXXXX
Temporary file for the file lengths.
.El

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr git 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
