.Dd July 22, 2017
.Dt TFLT 1
.Os

.Sh NAME
.Nm tflt
.Nd time line count

.Sh SYNOPSIS
.Nm tlc
.Ar filter
.Ar file

.Sh DESCRIPTION
.Nm
pipes
.Ar file
through
.Ar filter
for each commit, from the earliest to the latest.

.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/tlc.XXXXXX
Temporary file for the file lengthts.
.El
.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr git 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
